package crontab

import (
	"strings"
	"testing"

	"github.com/a-holm/paceq/internal/spec"
)

// roundTrip emits docs and parses every document back through spec.Parse,
// which refuses unknown fields by construction. This is the round-trip
// guarantee in miniature; the corpus test scales it to every fixture.
func roundTrip(t *testing.T, res Result) []string {
	t.Helper()
	var b strings.Builder
	if err := Emit(res.Docs, []string{"Generated by `paceq import crontab`."}, &b); err != nil {
		t.Fatalf("emit: %v", err)
	}
	stream := b.String()
	docs := SplitDocuments(stream)
	if len(docs) != len(res.Docs) {
		t.Fatalf("split produced %d documents from %d jobs", len(docs), len(res.Docs))
	}
	for i, doc := range docs {
		job, diags := spec.Parse("doc"+string(rune('0'+i))+".yaml", []byte(doc))
		if job == nil || diags.HasErrors() {
			var msgs []string
			for _, d := range diags {
				msgs = append(msgs, d.Message)
			}
			t.Fatalf("generated document does not parse:\n%s\n--- diagnostics:\n%s",
				doc, strings.Join(msgs, "\n"))
		}
	}
	return docs
}

// The issue's worked example, end to end: in-crontab and out-YAML.
func TestEmitIssueExampleRoundTrips(t *testing.T) {
	res := Import([]byte(strings.Join([]string{
		"CRON_TZ=Europe/Oslo",
		"MAILTO=drift@example.com",
		"PATH=/usr/local/bin:/usr/bin:/bin",
		"",
		"# nightly report",
		"0 2 * * * cd /srv/rapport && ./generer.sh > /dev/null 2>&1",
		"*/5 * * * * flock -n /var/lock/sync.lock /usr/local/bin/sync-files",
		"@daily /usr/local/bin/rydd-tmp",
		"17 3 * * 1 /usr/bin/psql -c 'VACUUM ANALYZE' >> /var/log/vacuum.log 2>&1",
		"0 4 * * * /opt/rapport/kjor.sh --dato=$(date +\\%Y-\\%m-\\%d)",
	}, "\n")+"\n"), Options{})

	if len(res.Docs) != 5 {
		t.Fatalf("docs = %d, want 5", len(res.Docs))
	}
	names := make(map[string]bool)
	for _, d := range res.Docs {
		names[d.Name] = true
	}
	for _, want := range []string{"generer", "sync-files", "rydd-tmp", "psql", "kjor"} {
		if !names[want] {
			t.Errorf("missing derived name %q in %v", want, names)
		}
	}
	roundTrip(t, res)
}

func TestEmitKeepsOriginalLineAboveEveryJob(t *testing.T) {
	res := Import([]byte("0 6 * * * /usr/bin/backup --full\n"), Options{})
	docs := roundTrip(t, res)
	if !strings.Contains(docs[0], "# originally: 0 6 * * * /usr/bin/backup --full") {
		t.Fatalf("origin line missing:\n%s", docs[0])
	}
}

func TestEmitHeaderAndSeparators(t *testing.T) {
	res := Import([]byte("0 6 * * * /bin/a\n30 7 * * * /bin/b\n"), Options{})
	var b strings.Builder
	if err := Emit(res.Docs, []string{"line one", "line two"}, &b); err != nil {
		t.Fatal(err)
	}
	out := b.String()
	if !strings.HasPrefix(out, "# line one\n# line two\n") {
		t.Fatalf("header missing:\n%s", out)
	}
	if got := strings.Count(out, "\n---\n"); got != 1 && !strings.Contains(out, "---") {
		t.Fatalf("separators wrong:\n%s", out)
	}
}

func TestSplitDocumentsIgnoresLeadingHeader(t *testing.T) {
	stream := "# header\n\n---\nname: a\nsteps: []\n---\nname: b\n"
	docs := SplitDocuments(stream)
	if len(docs) != 2 {
		t.Fatalf("docs = %d: %q", len(docs), docs)
	}
}

func TestReportRenderShape(t *testing.T) {
	src := strings.Join([]string{
		"# comment only lines count as read",
		"CRON_TZ=Europe/Oslo",
		"MAILTO=x@y.z",
		"0 2 * * * /bin/a > /dev/null 2>&1",
		"*/5 * * * * flock -n /l /bin/b",
		"@reboot /bin/c",
		"garbage line indeed",
	}, "\n") + "\n"
	res := Import([]byte(src), Options{})
	var b strings.Builder
	res.Report.Render(&b, UnicodeSymbols, []string{"paceq validate jobs/", "paceq import crontab --shadow"})
	out := b.String()
	for _, want := range []string{
		"7 lines read -> 4 jobs, 2 to review",
		"1 job threw output into /dev/null (the log is kept from now on)",
		"flock -> replaced with max_concurrent: 1",
		"@reboot -> paceq has no boot trigger yet",
		"line could not be interpreted",
		"Next steps:  paceq validate jobs/",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("report missing %q:\n%s", want, out)
		}
	}
}
