package cli

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// docsEnv is the inert environment the documentation tree is built on. The
// generator renders structure, never behaviour, so every edge is a discard
// and nothing reads the real process environment.
func docsEnv() Env {
	return Env{
		Stdout: io.Discard,
		Stderr: io.Discard,
		Getenv: func(string) string { return "" },
	}
}

// RenderCLIDocs returns the generated CLI reference page: one section per
// command of the real command tree, with its long help and its flags. It is
// a projection of this package's cobra definitions and nothing else, which
// is what makes the freshness gate in clidocs_test.go meaningful: hand edits,
// or help changes without regenerating, fail the build with the one command
// that fixes it. The output carries no date or version, so regenerating on
// an unchanged tree is byte-stable and diffs stay readable.
//
//go:generate go run ../../tools/gendocs
func RenderCLIDocs() string {
	var b strings.Builder
	b.WriteString(`<!-- Generated by go generate ./internal/cli from the cobra command tree.
     Do not edit by hand: the change will be overwritten and CI fails on the drift.
     Regenerate with: go generate ./internal/cli -->

# CLI reference

Every command, its flags and its long help, generated from the same code the
binary runs - so this page says exactly what the version you have installed
says. Data goes to stdout, progress and warnings to stderr; output follows the
stream (a terminal gets human text, a pipe gets JSON) unless -o picks a side.

Exit codes are a contract of their own: see [exit codes](exit-codes.md).

`)
	root := newRoot(docsEnv())
	b.WriteString(renderCommand(root, true))
	for _, child := range sortedCommands(root) {
		writeCommand(&b, child)
	}
	return b.String()
}

// sortedCommands orders one level of the tree by name. Cobra keeps insertion
// order internally; sorting here makes the page independent of registration
// order, so moving an AddCommand line cannot churn the reference.
func sortedCommands(cmd *cobra.Command) []*cobra.Command {
	children := cmd.Commands()
	out := make([]*cobra.Command, 0, len(children))
	out = append(out, children...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name() < out[j].Name() })
	return out
}

// renderCommand renders the root itself: its long help and the shared flags.
func renderCommand(root *cobra.Command, _ bool) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## `%s`\n\n", root.CommandPath())
	if long := root.Long; long != "" {
		b.WriteString(strings.TrimRight(long, "\n") + "\n\n")
	}
	writeFlags(&b, "Global flags", localPersistentFlags(root))
	return b.String()
}

// writeCommand renders one command section and recurses. Subcommands nest as
// deeper headings, so the page reads top down exactly like `--help` does.
func writeCommand(b *strings.Builder, cmd *cobra.Command) {
	depth := strings.Count(cmd.CommandPath(), " ")
	fmt.Fprintf(b, "%s `%s`\n\n", strings.Repeat("#", depth+2), cmd.CommandPath())
	if short := cmd.Short; short != "" && short != cmd.Long {
		b.WriteString(short + "\n\n")
	}
	if long := cmd.Long; long != "" {
		b.WriteString(strings.TrimSpace(long) + "\n\n")
	}
	if example := cmd.Example; example != "" {
		fmt.Fprintf(b, "Examples:\n\n```text\n%s\n```\n\n", strings.TrimSpace(example))
	}
	fmt.Fprintf(b, "Usage:\n\n    %s\n\n", cmd.UseLine())
	writeFlags(b, "Flags", cmd.LocalFlags())
	if inherited := inheritedFlags(cmd); len(visibleFlagNames(inherited)) > 0 {
		writeFlags(b, "Inherited flags", inherited)
	}
	for _, child := range sortedCommands(cmd) {
		writeCommand(b, child)
	}
}

// localPersistentFlags is the persistent flag set a command declares for its
// own subtree - on the root, the global flags every command inherits.
func localPersistentFlags(cmd *cobra.Command) *pflag.FlagSet {
	set := pflag.NewFlagSet("persistent", pflag.ContinueOnError)
	cmd.PersistentFlags().VisitAll(func(f *pflag.Flag) { set.AddFlag(f) })
	return set
}

// inheritedFlags collects persistent flags from every ancestor, so a
// subcommand's section shows where `-o` comes from without repeating the
// definition. A name the command declares itself is not inherited: cobra
// parses the local flag, and listing the ancestor's beside it would document
// a flag that never takes effect there.
func inheritedFlags(cmd *cobra.Command) *pflag.FlagSet {
	set := pflag.NewFlagSet("inherited", pflag.ContinueOnError)
	own := cmd.LocalFlags()
	for p := cmd.Parent(); p != nil; p = p.Parent() {
		local := localPersistentFlags(p)
		local.VisitAll(func(f *pflag.Flag) {
			if set.Lookup(f.Name) == nil && own.Lookup(f.Name) == nil {
				set.AddFlag(f)
			}
		})
	}
	return set
}

// visibleFlagNames lists a flag set's non-hidden names, sorted. Sorting here
// keeps the page independent of registration order.
func visibleFlagNames(flags *pflag.FlagSet) []string {
	names := make([]string, 0, 8)
	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		names = append(names, f.Name)
	})
	sort.Strings(names)
	return names
}

// writeFlags renders one flag set as a table, sorted by name. Hidden flags
// stay hidden: the page agrees with --help, which hides them too.
func writeFlags(b *strings.Builder, heading string, flags *pflag.FlagSet) {
	names := visibleFlagNames(flags)
	if len(names) == 0 {
		return
	}
	sort.Strings(names)
	fmt.Fprintf(b, "%s:\n\n", heading)
	fmt.Fprintf(b, "| Flag | | Meaning |\n|---|---|---|\n")
	for _, name := range names {
		f := flags.Lookup(name)
		shorthand := f.Shorthand
		if shorthand == "" {
			shorthand = " "
		}
		usage := strings.ReplaceAll(strings.TrimSpace(f.Usage), "\n", " ")
		fmt.Fprintf(b, "| `--%s` | `-%s` | %s |\n", f.Name, shorthand, usage)
	}
	b.WriteString("\n")
}
