package cli

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/a-holm/paceq/internal/importer/crontab"
)

// newImportCmd builds the import group. One verb per source system, of which
// crontab ships first.
func newImportCmd(env Env, g *globals) *cobra.Command {
	importCmd := &cobra.Command{
		Use:   "import",
		Short: "Bring existing schedules into paceq job files",
		Long: `Translate schedules another scheduler already runs into paceq job files.

Every import is read-only towards its source: a crontab is opened for
reading and nothing else. paceq never writes to a crontab and never calls
crontab with anything but the list flag.`,
	}

	var (
		fileFlag   string
		userFlag   string
		allUsers   bool
		tz         string
		namePrefix string
		output     string
		force      bool
	)

	cronCmd := &cobra.Command{
		Use:   "crontab",
		Short: "Translate a crontab into readable job files",
		Long: `Read a crontab and write the equivalent as paceq job YAML.

The source:

  (default)    your own crontab, exactly what ` + "`crontab -l`" + ` prints
  --file PATH  any crontab-format file, including /etc/crontab and the
               six-field files under /etc/cron.d (the user column is read)
  --user NAME  another user's crontab, via ` + "`crontab -u NAME -l`" + `
  --all-users  every crontab in the spool directory; needs root

The translation goes to stdout as readable YAML, one document per job, with
the original line kept as a comment above each job. The import report goes
to stderr, so this stays pure YAML on stdout:

  paceq import crontab > imported.yaml

-o names where the files go. A directory receives one .yaml file per job,
which is the shape validate and apply take directly. A file name receives
the whole annotated stream for reading and editing. An existing target is
refused unless --force is given.

What the translation does, line by line: five-field schedules become
schedules entries, @daily and friends become their cron expressions,
@reboot becomes an unscheduled job marked for review, flock wrappers
become max_concurrent: 1, output redirected to /dev/null is dropped with
a warning because the log is kept now, cd X && cmd becomes workdir plus an
absolute command, and commands with shell metacharacters stay whole behind
shell: true with a TODO comment. A percent sign keeps its cron meaning:
everything after the first unescaped one becomes the command's standard
input, carried over verbatim.

Nothing here runs a job or touches the database. Import produces files;
apply takes them in.`,
		Args: noArgs,
		RunE: runE(env, g, func(ctx context.Context, out *ui) error {
			return runImportCrontab(importOptions{
				file:       fileFlag,
				user:       userFlag,
				allUsers:   allUsers,
				timezone:   tz,
				namePrefix: namePrefix,
				output:     output,
				force:      force,
			}, out)
		}),
	}

	cronCmd.Flags().StringVar(&fileFlag, "file", "", "read this crontab file instead of running crontab -l")
	cronCmd.Flags().StringVar(&userFlag, "user", "", "read this user's crontab")
	cronCmd.Flags().BoolVar(&allUsers, "all-users", false, "read every crontab in the spool directory (root only)")
	cronCmd.Flags().StringVar(&tz, "tz", "", "timezone assumed where the file sets none (IANA name)")
	cronCmd.Flags().StringVar(&namePrefix, "name-prefix", "", "prefix every derived job name")
	cronCmd.Flags().StringVarP(&output, "output", "o", "", "write to this directory (one file per job) or file (whole stream)")
	cronCmd.Flags().BoolVar(&force, "force", false, "overwrite an existing -o target")

	cronCmd.MarkFlagsMutuallyExclusive("file", "user")
	cronCmd.MarkFlagsMutuallyExclusive("file", "all-users")
	cronCmd.MarkFlagsMutuallyExclusive("user", "all-users")

	importCmd.AddCommand(cronCmd)
	return importCmd
}

type importOptions struct {
	file       string
	user       string
	allUsers   bool
	timezone   string
	namePrefix string
	output     string
	force      bool
}

// crontabSource is one crontab as it was read.
type crontabSource struct {
	label    string // what messages call it
	user     string // namespace the job names carry, "" for none
	data     []byte
	sixField bool // read as /etc/crontab style: a user column on every entry
}

func runImportCrontab(opts importOptions, out *ui) error {
	sources, err := readSources(opts, out)
	if err != nil {
		return err
	}

	var docs []crontab.Doc
	report := crontab.Report{}
	for _, src := range sources {
		res := crontab.Import(src.data, crontab.Options{
			NamePrefix: joinPrefixes(opts.namePrefix, src.user),
			Timezone:   opts.timezone,
			SixField:   src.sixField,
		})
		docs = append(docs, res.Docs...)
		report = report.Plus(res.Report)
	}

	header := []string{
		"Generated by `paceq import crontab`.",
		"The original crontab was only read, never written.",
		"Review the TODO comments before you run `paceq apply`.",
	}

	nextSteps, err := writeImportOutput(docs, header, opts, out)
	if err != nil {
		return err
	}

	sym := crontab.Symbols{Warn: out.symbols.warn, Info: "ⓘ"}
	if out.symbols.warn != "⚠" {
		sym.Info = "NOTE"
	}
	report.Render(out.err, sym, nextSteps)
	return nil
}

// joinPrefixes combines --name-prefix with a per-user namespace so two
// users' backup jobs cannot collide into one name.
func joinPrefixes(flag, user string) string {
	if user == "" {
		return flag
	}
	prefix := user + "-"
	if flag != "" {
		prefix = flag + "-" + user + "-"
	}
	return prefix
}

// writeImportOutput sends the YAML where it belongs and returns the
// next-step lines the report ends with.
func writeImportOutput(docs []crontab.Doc, header []string, opts importOptions, out *ui) ([]string, error) {
	shadow := "paceq import crontab --shadow      # run alongside cron without executing anything (v0.2)"

	if opts.output == "" {
		if err := crontab.Emit(docs, header, out.out); err != nil {
			return nil, internalError("could not write the translated jobs", err)
		}
		out.note(1, "%d jobs translated; the report below went to stderr", len(docs))
		return []string{
			"paceq import crontab -o jobs/    writes one file per job, ready to check",
			"paceq validate jobs/",
			shadow,
		}, nil
	}

	info, err := os.Stat(opts.output)
	switch {
	case err == nil && info.IsDir():
		return writeJobDir(opts.output, docs, header, opts.force, shadow)
	case err == nil:
		if !opts.force {
			return nil, validationError(fmt.Sprintf("%s already exists", opts.output),
				errors.New("refusing to overwrite an existing file"),
				"pass --force to replace it, or name a directory to get one file per job:",
				"    paceq import crontab -o "+opts.output+"/")
		}
	case errors.Is(err, os.ErrNotExist):
		if looksLikeDirectory(opts.output) {
			if mkErr := os.MkdirAll(opts.output, 0o700); mkErr != nil {
				return nil, internalError("could not create the output directory", mkErr)
			}
			return writeJobDir(opts.output, docs, header, opts.force, shadow)
		}
	default:
		return nil, internalError("could not look at the output target", err)
	}

	// A single file takes the whole annotated stream.
	var b strings.Builder
	if err := crontab.Emit(docs, header, &b); err != nil {
		return nil, internalError("could not render the translated jobs", err)
	}
	if werr := os.WriteFile(opts.output, []byte(b.String()), 0o600); werr != nil {
		return nil, internalError("could not write "+opts.output, werr)
	}
	out.note(1, "wrote %d jobs to %s", len(docs), opts.output)
	if len(docs) == 1 {
		return []string{"paceq validate " + opts.output, shadow}, nil
	}
	return []string{
		opts.output + " holds one YAML document per job; move each into its own .yaml file",
		"or re-run with -o " + opts.output + "/ to have paceq write the files for you",
		shadow,
	}, nil
}

// looksLikeDirectory decides whether an unbuilt -o target wants the
// one-file-per-job treatment: a trailing separator says directory.
func looksLikeDirectory(path string) bool {
	return strings.HasSuffix(path, string(filepath.Separator))
}

func writeJobDir(dir string, docs []crontab.Doc, header []string, force bool, shadow string) ([]string, error) {
	var conflicts []string
	for i := range docs {
		path := filepath.Join(dir, docs[i].Name+".yaml")
		if _, err := os.Stat(path); err == nil && !force {
			conflicts = append(conflicts, path)
		}
	}
	if len(conflicts) > 0 {
		return nil, validationError(
			fmt.Sprintf("%s already exists (%d clash(es) in all)", conflicts[0], len(conflicts)),
			errors.New("refusing to overwrite existing job files"),
			"pass --force to replace them, or pick another directory:",
			"    paceq import crontab -o other-jobs/")
	}
	for i := range docs {
		var b strings.Builder
		if err := crontab.EmitDoc(&docs[i], &b); err != nil {
			return nil, internalError("could not render a job file", err)
		}
		path := filepath.Join(dir, docs[i].Name+".yaml")
		if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
			return nil, internalError("could not write "+path, err)
		}
	}
	return []string{"paceq validate " + dir, "paceq apply " + dir, shadow}, nil
}

// readSources resolves the source flags into crontabs to translate. Every
// path here is read-only: crontab(1) runs with -l and nothing else, and
// files are opened for reading only.
func readSources(opts importOptions, out *ui) ([]crontabSource, error) {
	switch {
	case opts.file != "":
		data, err := os.ReadFile(opts.file) // #nosec G304 - the path is what the operator asked paceq to read
		if err != nil {
			if errors.Is(err, os.ErrNotExist) {
				return nil, notFoundError("no crontab file at "+opts.file, "",
					"check the path, or import your own crontab instead:",
					"    paceq import crontab")
			}
			return nil, validationError("could not read "+opts.file, err,
				"check the permissions on the file:")
		}
		return []crontabSource{{label: opts.file, data: data, sixField: systemCrontabPath(opts.file)}}, nil

	case opts.user != "":
		data, err := runCrontabList(opts.user)
		if err != nil {
			return nil, err
		}
		return []crontabSource{{label: "user " + opts.user, data: data}}, nil

	case opts.allUsers:
		if os.Geteuid() != 0 {
			return nil, usageError("--all-users reads the spool directory, and only root may see it",
				"run it as root:",
				"    sudo paceq import crontab --all-users",
				"or import one user's crontab:",
				"    paceq import crontab --user <name>")
		}
		dir, found := spoolDir()
		if !found {
			return nil, notFoundError("no crontab spool directory on this machine", "",
				"looked at /var/spool/cron/crontabs and /var/spool/cron/tabs",
				"import a file instead:",
				"    paceq import crontab --file /etc/crontab")
		}
		entries, err := os.ReadDir(dir)
		if err != nil {
			return nil, internalError("could not read the spool directory", err)
		}
		var sources []crontabSource
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			data, rerr := os.ReadFile(filepath.Join(dir, e.Name())) // #nosec G304 - spool entries are the users' own crontabs, listed from ReadDir
			if rerr != nil {
				fmt.Fprintf(out.err, "skipping %s: %v\n", e.Name(), rerr)
				continue
			}
			sources = append(sources, crontabSource{label: "user " + e.Name(), user: e.Name(), data: data})
		}
		if len(sources) == 0 {
			return nil, notFoundError("the spool directory holds no crontabs", dir,
				"nothing to import yet; import a file instead:",
				"    paceq import crontab --file /etc/crontab")
		}
		return sources, nil

	default:
		data, err := runCrontabList("")
		if err != nil {
			return nil, err
		}
		return []crontabSource{{label: "current user", data: data}}, nil
	}
}

// systemCrontabPath reports whether a --file path is one of the files cron
// itself writes in the six-field form. Those get the user-column reading
// without guessing.
func systemCrontabPath(path string) bool {
	if path == "/etc/crontab" {
		return true
	}
	return strings.HasPrefix(path, "/etc/cron.d/")
}

// spoolDir finds where this cron keeps user crontabs.
func spoolDir() (string, bool) {
	for _, dir := range []string{"/var/spool/cron/crontabs", "/var/spool/cron/tabs"} {
		if info, err := os.Stat(dir); err == nil && info.IsDir() {
			return dir, true
		}
	}
	return "", false
}

// runCrontabList asks crontab(1) to print a crontab. It is the only way this
// command ever invokes crontab, and the argument list proves it: -l, with at
// most a user name beside it.
func runCrontabList(user string) ([]byte, error) {
	bin, err := exec.LookPath("crontab")
	if err != nil {
		return nil, notFoundError("the crontab command is not on PATH", "",
			"install a cron daemon, or import a file instead:",
			"    apt install cron    (or: dnf install cronie)",
			"    paceq import crontab --file /etc/crontab")
	}
	args := []string{"-l"}
	label := "your crontab"
	if user != "" {
		args = []string{"-u", user, "-l"}
		label = "a crontab for " + user
	}
	cmd := exec.Command(bin, args...)
	outBytes, runErr := cmd.Output()
	if runErr == nil {
		return outBytes, nil
	}
	var exitErr *exec.ExitError
	if errors.As(runErr, &exitErr) {
		message := strings.TrimSpace(string(exitErr.Stderr))
		if strings.Contains(message, "no crontab for") {
			return nil, notFoundError(message, "",
				"cron has nothing saved for this user yet; import a file instead:",
				"    paceq import crontab --file <path-to-a-crontab>")
		}
		if message == "" {
			message = fmt.Sprintf("crontab exited with %s", exitErr)
		}
		return nil, validationError("could not read "+label, errors.New(message),
			"reading another user's crontab needs root:",
			"    sudo paceq import crontab --user <name>")
	}
	return nil, internalError("could not run crontab", runErr)
}
