package reason

import (
	"fmt"
	"strings"
)

// levelOrder is the order the generated page and `paceq error --list` group
// by: the direction data flows, tick to step. It is fixed here rather than
// sorted, so reordering the levels is a visible diff and not a surprise.
var levelOrder = []Level{LevelTick, LevelTrigger, LevelRun, LevelStep, LevelLease}

// levelIntro is the one line under each level heading on the generated page.
var levelIntro = map[Level]string{
	LevelTick:    "Codes stored in the ticks table, one row per evaluation that was due.",
	LevelTrigger: "Codes stored in the triggers table, one row per trigger a tick produced.",
	LevelRun:     "Codes stored on the runs table, one row per run.",
	LevelStep:    "Codes stored on the steps table, one row per step of a run.",
	LevelLease:   "Codes stored in the lease_events table, one row per moment a role lease changed.",
}

// Render draws docs/reference/reason-codes.md from the catalogue and nothing
// else. It is the single writer of the page: the generator calls it, and the
// staleness test compares the checked in file against it, so the page cannot
// drift from the code it documents.
func Render() string {
	var b strings.Builder
	b.WriteString("<!-- Generated by go generate ./internal/reason from internal/reason/codes.go.\n")
	b.WriteString("     Do not edit by hand: the change will be overwritten and CI fails on the drift. -->\n\n")
	b.WriteString("# Reason codes\n\n")
	b.WriteString("Every reason code paceq can store in a reason_code column, what it means, and what\n")
	b.WriteString("to do about it. The catalogue is closed and stable: codes are added, never given a\n")
	b.WriteString("second meaning, and there is no UNKNOWN code to reach for.\n\n")
	b.WriteString("Each code carries a short text (for lists), a long explanation (for\n")
	b.WriteString("`paceq error <code>`), a remediation hint, and the keys it promises in\n")
	b.WriteString("reason_data. \"Ends the object\" marks the codes whose object is finished when the\n")
	b.WriteString("code is written; those are exactly the writes the schema refuses without a code.\n\n")
	b.WriteString("See also: `paceq error <code>` prints one entry, `paceq error --list -o json`\n")
	b.WriteString("prints the whole catalogue for machines.\n")

	for _, l := range levelOrder {
		fmt.Fprintf(&b, "\n## %s level\n\n%s\n\n", levelHeading(l), levelIntro[l])
		b.WriteString("| Code | Meaning | Ends the object | reason_data keys |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, e := range All() {
			if e.Level != l {
				continue
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
				e.Code, e.Short, endsObject(e), dataKeysCell(e))
		}
	}

	b.WriteString("\n## The codes in full\n")
	for _, l := range levelOrder {
		for _, e := range All() {
			if e.Level != l {
				continue
			}
			fmt.Fprintf(&b, "\n### %s\n\n", e.Code)
			fmt.Fprintf(&b, "%s. %s\n\n", e.Short, levelTag(e))
			b.WriteString(wrap(e.Explanation, 76))
			b.WriteString("\n\nWhat to do next:\n")
			for _, r := range e.Remedy {
				fmt.Fprintf(&b, "- %s\n", r)
			}
			if len(e.DataKeys) > 0 {
				fmt.Fprintf(&b, "\nPromised reason_data keys: %s.\n", strings.Join(e.DataKeys, ", "))
			}
		}
	}
	return b.String()
}

// levelHeading is the heading form of a level.
func levelHeading(l Level) string {
	switch l {
	case LevelTick:
		return "Tick"
	case LevelTrigger:
		return "Trigger"
	case LevelRun:
		return "Run"
	case LevelStep:
		return "Step"
	case LevelLease:
		return "Lease"
	}
	return string(l)
}

// levelTag is the bracketed tag under a full entry heading.
func levelTag(e Entry) string {
	if e.Terminal {
		return fmt.Sprintf("[%s level, ends the object]", e.Level)
	}
	return fmt.Sprintf("[%s level]", e.Level)
}

func endsObject(e Entry) string {
	if e.Terminal {
		return "yes"
	}
	return "no"
}

func dataKeysCell(e Entry) string {
	if len(e.DataKeys) == 0 {
		return "-"
	}
	keys := make([]string, 0, len(e.DataKeys))
	for _, k := range e.DataKeys {
		keys = append(keys, "`"+k+"`")
	}
	return strings.Join(keys, ", ")
}

// wrap breaks text at word boundaries near width, the way the CLI's plain
// text output does. It exists so the generated page reads the same on a plain
// terminal as everywhere else, and so the diff stays stable.
func wrap(text string, width int) string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return ""
	}
	var b strings.Builder
	line := words[0]
	for _, w := range words[1:] {
		if len(line)+1+len(w) > width {
			b.WriteString(line)
			b.WriteByte('\n')
			line = w
			continue
		}
		line += " " + w
	}
	b.WriteString(line)
	return b.String()
}
