package store

import (
	"context"
	"flag"
	"fmt"
	"os"
	"slices"
	"strings"
	"testing"
)

// updateGolden rewrites schema.golden.sql instead of comparing against it.
var updateGolden = flag.Bool("update", false, "rewrite schema.golden.sql from the migrated schema")

// goldenPath is the checked-in schema. It is the authoritative description of
// what a migrated database looks like, and reviewing a schema change means
// reading the diff to this file rather than replaying every migration.
const goldenPath = "schema.golden.sql"

// TestGoldenSchema fails on any change to the schema a fresh database ends up
// with, whether the change came from a new migration or an edited one.
func TestGoldenSchema(t *testing.T) {
	s := migratedStore(t)

	got := renderSchema(t, s)

	if *updateGolden {
		if err := os.WriteFile(goldenPath, []byte(got), 0o600); err != nil {
			t.Fatalf("write %s: %v", goldenPath, err)
		}
		return
	}

	raw, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read %s: %v\nregenerate it with: go test ./internal/store -run TestGoldenSchema -update", goldenPath, err)
	}
	if want := string(raw); want != got {
		t.Fatalf("the schema differs from %s.\nIs the change intended? Regenerate with: "+
			"go test ./internal/store -run TestGoldenSchema -update\n\n%s",
			goldenPath, diffLines(want, got))
	}
}

// objectRank orders the dump so the file can be replayed top to bottom: a table
// before the indexes on it, and everything before the triggers.
func objectRank(kind string) int {
	switch kind {
	case "table":
		return 0
	case "index":
		return 1
	case "view":
		return 2
	default:
		return 3
	}
}

// renderSchema is the schema as SQLite itself holds it, in a deterministic
// order. Objects SQLite maintains on its own carry no SQL text and are left
// out: they follow from the declarations that are in the file.
func renderSchema(t *testing.T, s *Store) string {
	t.Helper()

	ctx := context.Background()
	rows, err := s.w.QueryContext(ctx,
		`SELECT type, name, sql FROM sqlite_schema
			WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'`)
	if err != nil {
		t.Fatalf("read sqlite_schema: %v", err)
	}
	defer func() { _ = rows.Close() }()

	type object struct{ kind, name, sql string }
	var objects []object
	for rows.Next() {
		var o object
		if err := rows.Scan(&o.kind, &o.name, &o.sql); err != nil {
			t.Fatalf("scan sqlite_schema row: %v", err)
		}
		objects = append(objects, o)
	}
	if err := rows.Err(); err != nil {
		t.Fatalf("read sqlite_schema: %v", err)
	}
	slices.SortFunc(objects, func(a, b object) int {
		if r := objectRank(a.kind) - objectRank(b.kind); r != 0 {
			return r
		}
		return strings.Compare(a.name, b.name)
	})

	var out strings.Builder
	fmt.Fprintf(&out, "-- paceq schema at user_version %d.\n", userVersion(t, s))
	out.WriteString("-- Generated by: go test ./internal/store -run TestGoldenSchema -update\n")
	for _, o := range objects {
		out.WriteString("\n" + normaliseSQL(o.sql) + ";\n")
	}
	return out.String()
}

// normaliseSQL drops the whitespace SQLite preserved from the migration file so
// a reindented migration is not reported as a schema change.
func normaliseSQL(sql string) string {
	lines := strings.Split(strings.ReplaceAll(sql, "\r\n", "\n"), "\n")
	kept := lines[:0]
	for _, line := range lines {
		if line = strings.TrimRight(line, " \t"); line != "" {
			kept = append(kept, line)
		}
	}
	return strings.Join(kept, "\n")
}

// diffLines reports every line the two schemas disagree on, with line numbers,
// so a failure names the difference instead of printing two schemas to compare
// by eye.
func diffLines(want, got string) string {
	wantLines := strings.Split(want, "\n")
	gotLines := strings.Split(got, "\n")

	var out strings.Builder
	for i := 0; i < max(len(wantLines), len(gotLines)); i++ {
		w, g := lineAt(wantLines, i), lineAt(gotLines, i)
		if w == g {
			continue
		}
		if w != "" {
			fmt.Fprintf(&out, "%s:%d -%s\n", goldenPath, i+1, w)
		}
		if g != "" {
			fmt.Fprintf(&out, "%s:%d +%s\n", goldenPath, i+1, g)
		}
	}
	return out.String()
}

func lineAt(lines []string, i int) string {
	if i < len(lines) {
		return lines[i]
	}
	return ""
}
