package store

import (
	"fmt"
	"sort"
	"strings"
)

// RenderCatalogueDoc is the invariant reference page, projected from the
// catalogue and nothing else. The generator writes it (go generate ./internal/store)
// and the staleness test compares it, so the documentation cannot drift from
// the sweep: a remedy changed in code and not regenerated fails the build.
func RenderCatalogueDoc() string {
	var b strings.Builder
	b.WriteString(`<!-- Generated by go generate ./internal/store from internal/store/invariants.go.
     Do not edit by hand: the change will be overwritten and CI fails on the drift. -->

# Invariants

Every named rule ` + "`paceq fsck`" + ` checks, what a finding means, and what to do
about it. The catalogue lives in internal/store/invariants.go beside the
sweep itself; this page is generated from it, so a check that changes here
changes there too.

## Severity

| Grade | Meaning | What happens |
|---|---|---|
| critical | a uniqueness rule or the dependency graph is broken: a hand edit or corruption, not a bug paceq can reason around | the daemon refuses to start; ` + "`paceq fsck --repair --confirm`" + ` repairs what is repairable, after the operator confirms |
| serious | state drift the system can reconcile out of: a dead lease, a step outliving its run | an event is recorded and monitoring sees it; the daemon keeps serving |
| warning | cosmetic or historic: rows an older paceq wrote differently | reported and logged; nothing refuses |

## The catalogue

`)
	byID := make([]Invariant, len(Invariants))
	copy(byID, Invariants)
	sort.Slice(byID, func(i, j int) bool { return byID[i].ID < byID[j].ID })
	for _, inv := range byID {
		fmt.Fprintf(&b, "### %s — %s\n\n", inv.ID, inv.Title)
		fmt.Fprintf(&b, "Severity: **%s**.\n\n%s\n\n", inv.Severity, inv.Remedy)
	}
	return b.String()
}
