-- paceq schema at user_version 15.
-- Generated by: go test ./internal/store -run TestGoldenSchema -update

CREATE TABLE artifacts (
  id         TEXT    PRIMARY KEY,
  run_id     TEXT    NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
  step_name  TEXT,
  name       TEXT    NOT NULL,
  uri        TEXT    NOT NULL,
  size_bytes INTEGER,
  checksum   TEXT,
  meta_json  TEXT    NOT NULL DEFAULT '{}',
  created_at INTEGER NOT NULL,
  UNIQUE (run_id, name)
) STRICT;

CREATE TABLE daemon_sessions (
  id           TEXT    PRIMARY KEY,
  version      TEXT    NOT NULL,
  boot_id      TEXT,
  pid          INTEGER NOT NULL,
  started_at   INTEGER NOT NULL,
  last_seen_at INTEGER NOT NULL,
  stopped_at   INTEGER,
  stop_reason  TEXT CHECK (stop_reason IS NULL OR stop_reason IN ('clean', 'crash', 'replaced'))
) STRICT;

CREATE TABLE job_versions (
  id          TEXT    PRIMARY KEY,
  job_name    TEXT    NOT NULL REFERENCES jobs (name) ON DELETE CASCADE,
  version     INTEGER NOT NULL,
  spec_hash   TEXT    NOT NULL,
  spec_json   TEXT    NOT NULL,
  source_path TEXT,
  created_at  INTEGER NOT NULL,
  UNIQUE (job_name, version),
  UNIQUE (job_name, spec_hash)
) STRICT;

CREATE TABLE jobs (
  name               TEXT    PRIMARY KEY,
  -- Deferred because the two tables point at each other: a job's first version
  -- cannot exist before the job row, and the job cannot name it before it does.
  current_version_id TEXT    REFERENCES job_versions (id) DEFERRABLE INITIALLY DEFERRED,
  description        TEXT    NOT NULL DEFAULT '',
  paused             INTEGER NOT NULL DEFAULT 0 CHECK (paused IN (0, 1)),
  max_concurrent     INTEGER NOT NULL DEFAULT 1 CHECK (max_concurrent > 0),
  source_path        TEXT,
  created_at         INTEGER NOT NULL,
  updated_at         INTEGER NOT NULL
) STRICT;

CREATE TABLE lease_events (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  at          INTEGER NOT NULL,
  lease       TEXT    NOT NULL,
  holder      TEXT    NOT NULL,
  epoch       INTEGER NOT NULL CHECK (epoch > 0),
  reason_code TEXT    NOT NULL,
  detail_json TEXT    NOT NULL DEFAULT '{}'
) STRICT;

CREATE TABLE leases (
  name        TEXT    PRIMARY KEY,
  holder      TEXT    NOT NULL,
  epoch       INTEGER NOT NULL CHECK (epoch > 0),
  acquired_at INTEGER NOT NULL,
  expires_at  INTEGER NOT NULL
) STRICT, WITHOUT ROWID;

CREATE TABLE meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
) STRICT, WITHOUT ROWID;

CREATE TABLE outages (
  id           INTEGER PRIMARY KEY,
  from_ts      INTEGER NOT NULL,
  to_ts        INTEGER NOT NULL,
  detected_at  INTEGER NOT NULL,
  kind         TEXT    NOT NULL CHECK (kind IN ('crash', 'clean', 'clock_jump', 'boot')),
  prev_session TEXT REFERENCES daemon_sessions (id),
  missed_ticks INTEGER NOT NULL DEFAULT 0 CHECK (missed_ticks >= 0),
  CHECK (to_ts >= from_ts)
) STRICT;

CREATE TABLE outbox (
  id           INTEGER PRIMARY KEY,
  topic        TEXT    NOT NULL,               -- run.failed | run.succeeded | job.sla_breached
  subject      TEXT    NOT NULL,               -- job or sensor name (filtering + group_by)
  target       TEXT    NOT NULL,               -- named notifier from configuration
  payload      TEXT    NOT NULL,               -- JSON, serialised once at insertion
  dedup_key    TEXT    NOT NULL,               -- topic|subject|target|<event key>
  created_at   INTEGER NOT NULL,
  available_at INTEGER NOT NULL,
  attempts     INTEGER NOT NULL DEFAULT 0,
  delivered_at INTEGER,
  failed_at    INTEGER,                        -- permanent give-up after max_attempts
  last_error   TEXT
) STRICT;

CREATE TABLE outbox_windows (
  topic      TEXT    NOT NULL,
  target     TEXT    NOT NULL,
  group_key  TEXT    NOT NULL,
  opener_id  INTEGER NOT NULL,
  opened_at  INTEGER NOT NULL,
  suppressed INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (topic, target, group_key)
) STRICT;

CREATE TABLE run_events (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id      TEXT    NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
  -- Steps are keyed by (run_id, name), so this is the name alone rather than a
  -- foreign key. An event about a step that no longer exists still reads.
  step_name   TEXT,
  at          INTEGER NOT NULL,
  kind        TEXT    NOT NULL,
  from_state  TEXT,
  to_state    TEXT,
  reason_code TEXT,
  actor       TEXT    NOT NULL DEFAULT 'system',
  detail_json TEXT    NOT NULL DEFAULT '{}'
) STRICT;

CREATE TABLE run_keys (
  source_id     TEXT    NOT NULL,
  epoch         INTEGER NOT NULL,
  run_key       TEXT    NOT NULL,
  first_seen_at INTEGER NOT NULL,
  run_id        TEXT,
  PRIMARY KEY (source_id, epoch, run_key)
) STRICT, WITHOUT ROWID;

CREATE TABLE runs (
  id                  TEXT    PRIMARY KEY,
  job_name            TEXT    NOT NULL REFERENCES jobs (name) ON DELETE CASCADE,
  -- No ON DELETE: a version a run points at may not be deleted. Versions are
  -- tiny and are never swept, and without one a replay means nothing.
  job_version_id      TEXT    NOT NULL REFERENCES job_versions (id),
  trigger_id          TEXT    REFERENCES triggers (id) ON DELETE SET NULL,
  origin              TEXT    NOT NULL,
  run_key             TEXT,
  state               TEXT    NOT NULL,
  available_at        INTEGER NOT NULL,
  defer_reason        TEXT,
  scheduled_for       INTEGER,
  params_json         TEXT    NOT NULL DEFAULT '{}',
  concurrency_key     TEXT,
  attempt             INTEGER NOT NULL DEFAULT 0,
  max_attempts        INTEGER NOT NULL DEFAULT 1 CHECK (max_attempts >= 1),
  lease_owner         TEXT,
  -- The fencing token. Every result write proves the lease is still its own by
  -- carrying it, so a slow worker cannot overwrite what its replacement wrote.
  lease_epoch         INTEGER NOT NULL DEFAULT 0,
  lease_expires_at    INTEGER,
  heartbeat_at        INTEGER,
  cancel_requested_at INTEGER,
  cancel_reason       TEXT,
  crash_count         INTEGER NOT NULL DEFAULT 0,
  replay_of           TEXT    REFERENCES runs (id) ON DELETE SET NULL,
  reason_code         TEXT,
  reason_text         TEXT,
  reason_data         TEXT,
  error               TEXT,
  error_tail          TEXT,
  created_at          INTEGER NOT NULL,
  started_at          INTEGER,
  finished_at         INTEGER,
  duration_ms         INTEGER,
  updated_at          INTEGER NOT NULL, cancel_requested_by TEXT, max_parallel INTEGER NOT NULL DEFAULT 4
  CHECK (max_parallel >= 1),
  CHECK (origin IN ('schedule', 'sensor', 'manual', 'retry', 'replay', 'backfill')),
  CHECK (state IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  CHECK (defer_reason IS NOT NULL OR available_at <= created_at OR state <> 'queued'),
  CHECK (state IN ('queued', 'running') OR reason_code IS NOT NULL),
  CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at)
) STRICT;

CREATE TABLE schedules (
  id                TEXT    PRIMARY KEY,
  job_name          TEXT    NOT NULL REFERENCES jobs (name) ON DELETE CASCADE,
  name              TEXT    NOT NULL,
  kind              TEXT    NOT NULL CHECK (kind IN ('cron', 'interval')),
  expr              TEXT    NOT NULL,
  -- The one place a timezone is stored, because a cron expression has to be
  -- interpreted. Everything else is ordered, and ordering needs no timezone.
  timezone          TEXT    NOT NULL DEFAULT 'UTC',
  spring_forward    TEXT    NOT NULL DEFAULT 'skip'
                    CHECK (spring_forward IN ('skip', 'shift')),
  fall_back         TEXT    NOT NULL DEFAULT 'first'
                    CHECK (fall_back IN ('first', 'both')),
  catchup           TEXT    NOT NULL DEFAULT 'skip'
                    CHECK (catchup IN ('skip', 'last', 'all')),
  catchup_limit     INTEGER NOT NULL DEFAULT 10 CHECK (catchup_limit >= 0),
  catchup_window_ms INTEGER NOT NULL DEFAULT 86400000,
  paused            INTEGER NOT NULL DEFAULT 0 CHECK (paused IN (0, 1)),
  last_tick_at      INTEGER,
  next_tick_at      INTEGER NOT NULL,
  created_at        INTEGER NOT NULL,
  updated_at        INTEGER NOT NULL, overlap TEXT NOT NULL DEFAULT 'skip'
  CHECK (overlap IN ('skip', 'queue')), shadow INTEGER NOT NULL DEFAULT 0
  CHECK (shadow IN (0, 1)),
  UNIQUE (job_name, name)
) STRICT;

CREATE TABLE schema_migration_lock (
	id          INTEGER PRIMARY KEY CHECK (id = 1),
	holder      TEXT    NOT NULL,
	acquired_at INTEGER NOT NULL,
	expires_at  INTEGER NOT NULL
) STRICT;

CREATE TABLE schema_migrations (
	version    INTEGER PRIMARY KEY,
	name       TEXT    NOT NULL,
	checksum   TEXT    NOT NULL,
	applied_at INTEGER NOT NULL
) STRICT;

CREATE TABLE sensor_events (
  id          TEXT    PRIMARY KEY,
  sensor_name TEXT    NOT NULL,
  job_name    TEXT    NOT NULL,
  kind        TEXT    NOT NULL CHECK (kind IN ('removed', 'created', 'spec_changed')),
  at          INTEGER NOT NULL,
  detail_json TEXT
) STRICT;

CREATE TABLE sensors (
  name                  TEXT    PRIMARY KEY,
  job_name              TEXT    NOT NULL REFERENCES jobs (name) ON DELETE CASCADE,
  -- One adapter: a subprocess that writes JSON to stdout. A second kind is a
  -- migration and a new evaluator, not a flag somebody sets by accident.
  kind                  TEXT    NOT NULL DEFAULT 'exec' CHECK (kind = 'exec'),
  exec_json             TEXT    NOT NULL,
  interval_ms           INTEGER NOT NULL CHECK (interval_ms >= 1000),
  min_interval_ms       INTEGER NOT NULL DEFAULT 1000,
  timeout_ms            INTEGER NOT NULL DEFAULT 30000 CHECK (timeout_ms > 0),
  max_triggers_per_tick INTEGER NOT NULL DEFAULT 100 CHECK (max_triggers_per_tick > 0),
  paused                INTEGER NOT NULL DEFAULT 0 CHECK (paused IN (0, 1)),
  paused_reason         TEXT,
  cursor                TEXT,
  cursor_updated_at     INTEGER,
  -- Bumped when an operator resets the cursor. It is part of the dedup key, so
  -- a reset makes every run key new again instead of replaying into a table
  -- that has already seen all of them and silently dropping the lot.
  dedup_epoch           INTEGER NOT NULL DEFAULT 0,
  consecutive_failures  INTEGER NOT NULL DEFAULT 0,
  next_eval_at          INTEGER NOT NULL,
  created_at            INTEGER NOT NULL,
  updated_at            INTEGER NOT NULL
, cursor_version INTEGER NOT NULL DEFAULT 0, last_error TEXT, last_eval_at INTEGER, breaker_opened_at INTEGER, spec_json TEXT NOT NULL DEFAULT '{}') STRICT;

CREATE TABLE shadow_observations (
  id          INTEGER PRIMARY KEY,
  observed_at INTEGER NOT NULL,
  source      TEXT    NOT NULL CHECK (source IN ('journald', 'file', 'manual')),
  raw         TEXT    NOT NULL,
  command     TEXT,
  cron_user   TEXT,
  job_name    TEXT,
  UNIQUE(source, observed_at, raw)
) STRICT;

CREATE TABLE sla_episodes (
  job         TEXT    PRIMARY KEY,
  breached_at INTEGER NOT NULL
) STRICT;

CREATE TABLE step_deps (
  run_id     TEXT NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
  step_name  TEXT NOT NULL,
  depends_on TEXT NOT NULL,
  PRIMARY KEY (run_id, step_name, depends_on)
) STRICT, WITHOUT ROWID;

CREATE TABLE steps (
  run_id          TEXT    NOT NULL REFERENCES runs (id) ON DELETE CASCADE,
  name            TEXT    NOT NULL,
  -- Position in the spec. M1 runs steps in this order; M4 reads step_deps and
  -- keeps idx only as the tie break between steps that are equally ready.
  idx             INTEGER NOT NULL,
  state           TEXT    NOT NULL,
  attempt         INTEGER NOT NULL DEFAULT 0,
  max_attempts    INTEGER NOT NULL DEFAULT 1 CHECK (max_attempts >= 1),
  next_attempt_at INTEGER,
  started_at      INTEGER,
  finished_at     INTEGER,
  duration_ms     INTEGER,
  exit_code       INTEGER,
  signal          TEXT,
  error           TEXT,
  reason_code     TEXT,
  reason_text     TEXT,
  reason_data     TEXT,
  -- The log itself is a file. Only where it is, how big it got and whether it
  -- was cut off belong in the database.
  log_path        TEXT,
  log_bytes       INTEGER NOT NULL DEFAULT 0,
  log_truncated   INTEGER NOT NULL DEFAULT 0 CHECK (log_truncated IN (0, 1)),
  error_tail      TEXT, pid INTEGER, pid_start_ticks INTEGER,
  PRIMARY KEY (run_id, name),
  CHECK (state IN ('pending', 'running', 'succeeded', 'failed', 'skipped', 'cancelled')),
  CHECK (state IN ('pending', 'running') OR reason_code IS NOT NULL)
) STRICT;

CREATE TABLE "ticks" (
  id                TEXT    PRIMARY KEY,
  source_kind       TEXT    NOT NULL
                    CHECK (source_kind IN ('schedule', 'sensor', 'manual')),
  source_name       TEXT    NOT NULL,
  scheduled_for     INTEGER,
  started_at        INTEGER NOT NULL,
  last_started_at   INTEGER NOT NULL,
  finished_at       INTEGER,
  duration_ms       INTEGER,
  repeat_count      INTEGER NOT NULL DEFAULT 1 CHECK (repeat_count >= 1),
  outcome           TEXT    NOT NULL DEFAULT 'running'
                    CHECK (outcome IN ('running', 'triggered', 'skipped',
                                       'error', 'missed', 'shadow_triggered')),
  reason_code       TEXT,
  reason_text       TEXT,
  reason_data       TEXT,
  trigger_count     INTEGER NOT NULL DEFAULT 0,
  deduped_count     INTEGER NOT NULL DEFAULT 0,
  cursor_before     TEXT,
  cursor_after      TEXT,
  daemon_session_id TEXT,
  UNIQUE (source_kind, source_name, scheduled_for),
  CHECK (outcome IN ('running', 'triggered', 'shadow_triggered')
         OR reason_code IS NOT NULL)
) STRICT;

CREATE TABLE triggers (
  id          TEXT    PRIMARY KEY,
  tick_id     TEXT    NOT NULL REFERENCES ticks (id) ON DELETE CASCADE,
  job_name    TEXT    NOT NULL REFERENCES jobs (name) ON DELETE CASCADE,
  run_key     TEXT,
  params_json TEXT    NOT NULL DEFAULT '{}',
  created_at  INTEGER NOT NULL,
  outcome     TEXT    NOT NULL CHECK (outcome IN ('accepted', 'deduped', 'rejected')),
  reason_code TEXT,
  reason_text TEXT,
  -- On a deduped trigger this points at the original run, which is the answer
  -- to the only question anyone asks about a deduped trigger.
  run_id      TEXT    REFERENCES runs (id) ON DELETE SET NULL,
  CHECK (outcome = 'accepted' OR reason_code IS NOT NULL)
) STRICT;

CREATE INDEX daemon_sessions_open
  ON daemon_sessions (started_at DESC) WHERE stopped_at IS NULL;

CREATE INDEX idx_job_versions_job ON job_versions (job_name, version DESC);

CREATE INDEX idx_lease_events_lease ON lease_events (lease, id);

CREATE INDEX idx_outbox_pending ON outbox(available_at, id)
  WHERE delivered_at IS NULL AND failed_at IS NULL;

CREATE INDEX idx_outbox_subject ON outbox(subject, created_at DESC);

CREATE INDEX idx_outbox_windows_opener ON outbox_windows(opener_id);

CREATE INDEX idx_run_events_run ON run_events (run_id, id);

CREATE INDEX idx_run_keys_age ON run_keys (first_seen_at);

CREATE INDEX idx_runs_active   ON runs (job_name) WHERE state IN ('queued', 'running');

CREATE INDEX idx_runs_claim    ON runs (available_at, id) WHERE state = 'queued';

CREATE INDEX idx_runs_finished ON runs (finished_at) WHERE finished_at IS NOT NULL;

CREATE INDEX idx_runs_history  ON runs (job_name, id DESC);

CREATE INDEX idx_runs_job_finished ON runs (job_name, finished_at DESC, id DESC)
  WHERE finished_at IS NOT NULL;

CREATE INDEX idx_runs_reaper   ON runs (lease_expires_at) WHERE state = 'running';

CREATE INDEX idx_runs_replay_of ON runs (replay_of)
  WHERE replay_of IS NOT NULL;

CREATE INDEX idx_schedules_due ON schedules (next_tick_at) WHERE paused = 0;

CREATE INDEX idx_sensor_events_sensor ON sensor_events (sensor_name, at DESC);

CREATE INDEX idx_sensors_due ON sensors (next_eval_at) WHERE paused = 0;

CREATE INDEX idx_shadow_obs_job ON shadow_observations(job_name, observed_at);

CREATE INDEX idx_step_deps_upstream ON step_deps (run_id, depends_on);

CREATE INDEX idx_steps_claimable ON steps (run_id, idx) WHERE state = 'pending';

CREATE INDEX idx_steps_retry     ON steps (next_attempt_at)
  WHERE state = 'pending' AND next_attempt_at IS NOT NULL;

CREATE INDEX idx_ticks_age    ON ticks (started_at);

CREATE INDEX idx_ticks_bad    ON ticks (started_at DESC) WHERE outcome IN ('error', 'missed');

CREATE INDEX idx_ticks_source ON ticks (source_kind, source_name, started_at DESC);

CREATE INDEX idx_triggers_job  ON triggers (job_name, created_at DESC);

CREATE INDEX idx_triggers_run_id ON triggers (run_id)
  WHERE run_id IS NOT NULL;

CREATE INDEX idx_triggers_tick ON triggers (tick_id);

CREATE INDEX outages_by_time ON outages (from_ts DESC);

CREATE UNIQUE INDEX ux_outbox_dedup ON outbox(dedup_key);

CREATE UNIQUE INDEX ux_runs_conc_key ON runs (concurrency_key)
  WHERE concurrency_key IS NOT NULL AND state IN ('queued', 'running');

CREATE TRIGGER sensors_paused_needs_reason
BEFORE UPDATE OF paused ON sensors
WHEN NEW.paused = 1 AND (NEW.paused_reason IS NULL OR NEW.paused_reason = '')
BEGIN
  SELECT RAISE(ABORT, 'paused sensor uten paused_reason');
END;
