-- paceq schema at user_version 1.
-- Generated by: go test ./internal/store -run TestGoldenSchema -update

CREATE TABLE daemon_sessions (
  id           TEXT    PRIMARY KEY,
  version      TEXT    NOT NULL,
  boot_id      TEXT,
  pid          INTEGER NOT NULL,
  started_at   INTEGER NOT NULL,
  last_seen_at INTEGER NOT NULL,
  stopped_at   INTEGER,
  stop_reason  TEXT CHECK (stop_reason IS NULL OR stop_reason IN ('clean', 'crash', 'replaced'))
) STRICT;

CREATE TABLE leases (
  name        TEXT    PRIMARY KEY,
  holder      TEXT    NOT NULL,
  epoch       INTEGER NOT NULL CHECK (epoch > 0),
  acquired_at INTEGER NOT NULL,
  expires_at  INTEGER NOT NULL
) STRICT, WITHOUT ROWID;

CREATE TABLE meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
) STRICT, WITHOUT ROWID;

CREATE TABLE outages (
  id           INTEGER PRIMARY KEY,
  from_ts      INTEGER NOT NULL,
  to_ts        INTEGER NOT NULL,
  detected_at  INTEGER NOT NULL,
  kind         TEXT    NOT NULL CHECK (kind IN ('crash', 'clean', 'clock_jump', 'boot')),
  prev_session TEXT REFERENCES daemon_sessions (id),
  missed_ticks INTEGER NOT NULL DEFAULT 0 CHECK (missed_ticks >= 0),
  CHECK (to_ts >= from_ts)
) STRICT;

CREATE TABLE schema_migration_lock (
	id          INTEGER PRIMARY KEY CHECK (id = 1),
	holder      TEXT    NOT NULL,
	acquired_at INTEGER NOT NULL,
	expires_at  INTEGER NOT NULL
) STRICT;

CREATE TABLE schema_migrations (
	version    INTEGER PRIMARY KEY,
	name       TEXT    NOT NULL,
	checksum   TEXT    NOT NULL,
	applied_at INTEGER NOT NULL
) STRICT;

CREATE INDEX daemon_sessions_open
  ON daemon_sessions (started_at DESC) WHERE stopped_at IS NULL;

CREATE INDEX outages_by_time ON outages (from_ts DESC);
